### ISSUE TITLE
Warn if attr object sent in invalid form

### ISSUE THREAD

**Issue by davidandrus** [alfredkam/yakojs#28]
*broken:*  http://codepen.io/skatan/pen/jEQQKy
all but data needs to be wrapped in chart
expected: to be notified that attr config object not in the proper form:

```
yako.bubble().attr({
    height : ..., width : ..., data : ...
});
```
*working example:* http://codepen.io/skatan/pen/Joeewe
```
yako.bubble().attr({
    chart: { height : ..., width : ...},
    data : ...
});
```
If possible it might be nice to drop the chart prop all together if possible, as it might make the configuration a little more straight forward.

**Comment by hasalfred** [comment]
@davidandrus after giving some thoughts i'll look into removing the barrier in requiring ```chart``` for ```.attr()```

**Comment by alfredkam** [comment]
@davidandrus , now ```chart``` is not required - https://github.com/alfredkam/yakojs/commit/96ea8b0895af4050b9f915218360b4bea741b592#diff-1222d8f70c8406da404fd68f5b03b7aaR50
