### ISSUE TITLE
Sparkline should accept a scale

### ISSUE THREAD

**Issue by davidandrus** [alfredkam/yakojs#46]
see the example: http://codepen.io/skatan/pen/yNjgZo. 

It is desirable to plot a sparkline against a scale. In the example above I can see the case where you would want to show the flat sparkline in the vertical center of the svg, a scale would make this possible.

```
yako.spark().attr({
  width: 300,
  height: 100,
  points: [{
    data: [1, 1, 1, 1, 1, 1, 1],
    scale: [0, 2] // 0 is min 2 is max
  ]
  // scale: [0, 2] // possibly a scale for every data set since spark can have multiple
});
```

**Comment by alfredkam** [comment]
@davidandrus i should be able to implement a feasible strategy to support it.

**Comment by alfredkam** [comment]
@davidandrus give it a shot on monday to see if this works https://github.com/alfredkam/yakojs/tree/feature/scale-46

usage
```javascript
yako.spark().attr({
  width: 300,
  height: 100,
  yAxis: { multi: true },
  points: [{
    data: [1, 1, 1, 1, 1, 1, 1],
    scale: [0, 2] // 0 is min 2 is max
  ]
  // scale: [0, 2] // possibly a scale for every data set since spark can have multiple
});
```
