### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by seethroughtrees** [alfredkam/yakojs#58]
This project looks interesting, but demo links are broken.  ```gulp dev``` raises error.  And no updates in the last few months.

Is this project still being worked on?

**Comment by alfredkam** [comment]
thats weird, ill take a look. Ill get back to you shortly.

**Comment by alfredkam** [comment]
currently im trying to work out how to evolve it, and along side with the react changes that keeps pumping out.

**Comment by hasalfred** [comment]
@seethroughtrees fixed, please try again

**Comment by seethroughtrees** [comment]
Thanks for the quick response @alfredkam 

Yeah, its tough to keep up with React changes.  But happy that you took a shot at it.

The public link still shows an nginx error.  I pulled the repo ran ```npm i``` and ```gulp dev```  I don't get the error, but get nothing at localhost:3000.  I also tried running a local server at demo/ and that didn't work either.  Am I missing something?

**Comment by hasalfred** [comment]
check ```localhost:5000``` instead.

the public link is down - due to recently i've dockerized my site was moved, i will need to rewire the content.

**Comment by hasalfred** [comment]
@seethroughtrees 
please check ```localhost:5000``` instead.

the public link is down - due to recently i've dockerized my site was moved, i will need to rewire the content.

**Comment by hasalfred** [comment]
thanks for catching that

**Comment by seethroughtrees** [comment]
Worked perfect.  Thanks @hasalfred !
